# 学習データの保存場所
csv: '/home/akio/deaf_si/merge.csv'
# DataLoaderのパラメータ
batch_size: 1
num_workers: 1
# 学習時のパラメータ
trainer:
  accelerator: 'auto'
  accumulate_grad_batches: 5
  max_epochs: 200
  #precision: '16-mixed'
  profiler: 'simple'
  gradient_clip_val: 5.
optimizer:
  lr: 1.e-4
  weight_decay: 1.e-3
# ログの保存場所
logger:
  save_dir: './si_model/'
  version: 1
  name: 'your-model-name'
# 中間モデルの保存
checkpoint:
  monitor: 'valid_loss'
  filename: 'checkpoint_{epoch}-{step}-{valid_loss:.2f}'
  save_last: True
  save_top_k: 1
  mode: 'min'
  every_n_epochs: 1
loss:
  type: 'kappa' # 'mse', 'huber', 'kappa'
  delta: 0.5
model:
  input_dim: 1024
  output_dim: 256
  hidden_dim: 256
  proj_dim: 128
  num_layers: 1
  dropout: 0.0 # 0.0 if num_layers=1
  lora_attention_dim: 32
  lora_alpha: 16
  lora_dropout: 0.1
