# data
train_path: "smile/${SPEAKER}_train.csv"
valid_path: "smile/${SPEAKER}_valid.csv"
stat_path: ./stats.pt
batch_size: 4
epochs: 50

# process
process:
  batch_size: 4
  num_workers: 0

# trainer
trainer:
  max_epochs: 50
  profiler: 'simple'

# logger
logger:
  save_dir: '/media/akio/hdd1/si_model/smile_model/${SPEAKER}'
  version: 1
  name: 'lightning_logs'

# checkpoint
checkpoint:
  monitor: 'valid_acc'
  filename: 'checkpoint_{epoch}-{step}-{valid_acc:.3f}'
  save_last: True
  save_top_k: 1
  mode: 'max'
  every_n_epochs: 1

# generator optimizer
optimizer:
  lr: 1.e-4
  betas:
    - 0.9
    - 0.999
  weight_decay: 1.e-6

scheduler:
  mode: 'min'
  factor: 0.99
  patience: 5
  verbose: True
model:
  num_mfcc: 40
  num_smile_feats: 88
  gru_hidden_dim: 64
  embed_dim: 64
  num_classes: 9
output_path: model.pt
